//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mmm
{
    using mmm.Helpers;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Titre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Titre()
        {
            this.clients = new HashSet<client>();
            ListeVilles = new List<string>();
        }

        [Required(ErrorMessage = Constante.CHAMPS_OBLIGATOIRE)]
        public int Idtitre { get; set; }
        [Required(ErrorMessage = "la date est obligatoire")]
        [Display(Name = "datetitre")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> datetitre { get; set; }
        [Required(ErrorMessage = "Le prix est obligatoire.")]
        [Range(1, 200, ErrorMessage = "Le prix doit être compris entre 1 et 200.")]
        public Nullable<int> prixtitre { get; set; }
        [Required(ErrorMessage = "La ville est obligatoire.")]
        public string villetitre { get; set; }
        public List<string> ListeVilles { get; set; }
        public Nullable<int> idclient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<client> clients { get; set; }
        public virtual client client { get; set; }
    }
}
